from pipefunc import Pipeline, pipefunc


def test_axis_is_reduced_and_noannotation():
    @pipefunc("y", mapspec="x[i] -> y[i]")
    def f(x):
        return x

    @pipefunc("z")
    def g(y: list[int]) -> list[int]:
        return y

    Pipeline([f, g])


def test_returning_tuple_autogenerated_axis():
    # Mapspec is autogenerated
    @pipefunc(output_name=("x", "y"))
    def f() -> tuple[list[int], list[list[int]]]:
        return [1, 2, 3], [[1, 2], [3, 4]]

    # Uses elements of the lists in map
    @pipefunc(output_name="z", mapspec="x[i] -> z[i]")
    def g(x: int) -> int:
        return x

    # Takes entire list
    @pipefunc(output_name="zz")
    def h(x: list[int]) -> list[int]:
        return x

    Pipeline([f, g, h])
