name: codspeed

on:
  pull_request:
  push:
    branches: [main]
  # `workflow_dispatch` allows CodSpeed to trigger backtest
  # performance analysis in order to generate initial data.
  workflow_dispatch:

jobs:
  benchmark:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    env:
      python-version: "3.12"
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Update Python version in environment.yml
        run: |
          sed -i '/^\s*-\s*python\s*$/ s/$/=${{ env.python-version }}/' environment.yml
          echo "Updated environment.yml content:"
          cat environment.yml

      - name: Install Conda environment with micromamba
        uses: mamba-org/setup-micromamba@v2
        with:
          environment-file: environment.yml
          cache-environment: true

      - name: Install pipefunc
        shell: bash -l {0}
        run: |
          pip install -e ".[test,all]"
          # Otherwise, I get:
          # INTERNALERROR> ModuleNotFoundError: No module named 'pytest_codspeed.instruments.valgrind._wrapper.dist_callgrind_wrapper'
          pip uninstall -y pytest-timeout

      - name: Run benchmarks
        uses: CodSpeedHQ/action@v3
        with:
          token: ${{ secrets.CODSPEED_TOKEN }}
          run: |
            set -ex
            env
            micromamba run -n pipefunc \
              pytest tests/test_benchmark.py --codspeed
